name: dwarka_app
description: A Flutter app for a spectacle shop
publish_to: 'none' # Remove this line if you plan to publish on pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Flutter & UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  animations: ^2.0.11
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  flutter_rating: ^2.0.2

  # Navigation & Routing
  go_router: ^11.0.0

  # State Management
  provider: ^6.1.1

  # Storage & Data
  shared_preferences: ^2.2.2
  uuid: ^4.4.0

  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.15.1

  # Authentication
  google_sign_in: ^7.1.1
  font_awesome_flutter: ^10.9.1

  # File Handling
  file_picker: ^8.0.0
  image_picker: ^1.0.4

  # Icons
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/dwarka_logo.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/dwarka_logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/dwarka_logo.jpg
    - assets/images/profile_img.png
    - assets/images/categories/
    - assets/images/icons/
    - assets/images/products/